Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: main
      CodeUri: \\wsl$\Ubuntu\home\henry\workspace\terraform\cloud-nuke-centre
      Runtime: go1.x
      Architectures:
        - x86_64